src/main/java/comatching/comatching3/admin/entity/Admin.java
src/main/java/comatching/comatching3/admin/entity/University.java
src/main/java/comatching/comatching3/admin/enums/AdminRole.java
src/main/java/comatching/comatching3/history/entity/MatchingHistory.java
src/main/java/comatching/comatching3/history/entity/PointHistory.java
src/main/java/comatching/comatching3/match_message/entity/MessageMap.java
src/main/java/comatching/comatching3/users/entity/Quit.java
src/main/java/comatching/comatching3/users/entity/UserAiFeature.java
src/main/java/comatching/comatching3/users/entity/Users.java
src/main/java/comatching/comatching3/users/enums/ContactFrequency.java
src/main/java/comatching/comatching3/users/enums/Gender.java
src/main/java/comatching/comatching3/users/enums/Hobby.java
src/main/java/comatching/comatching3/users/enums/Major.java
src/main/java/comatching/comatching3/users/enums/Role.java
src/main/java/comatching/comatching3/util/HobbyListConverter.java

- 패키지 이름 변경 Users -> users
- Admin 관련 엔티티 추가
- Quit 엔티티 추가

엔티티 추가 및 패키지 이름 변경

---

src/main/java/comatching/comatching3/admin/entity/Admin.java
src/main/java/comatching/comatching3/admin/entity/University.java
src/main/java/comatching/comatching3/history/entity/MatchingHistory.java
src/main/java/comatching/comatching3/history/entity/PointHistory.java
src/main/java/comatching/comatching3/history/enums/PointHistoryType.java
src/main/java/comatching/comatching3/users/entity/Users.java

- 엔티티들 Builder 추가
- 유저 엔티티 수정
- 매칭 히스토리 컬럼명 변경
- 포인트 히스토리 enum에 환불 추가

CMT-11 채팅 제외 ERD 마무리

---

.gitignore
src/main/java/comatching/comatching3/util/Response.java
src/main/java/comatching/comatching3/util/ResponseCode.java

- Response 객체 추가 
- Respose Code 추가

CMT-13 Response 클래스 추가

---

src/main/java/comatching/comatching3/admin/repository/AdminRepository.java
src/main/java/comatching/comatching3/admin/repository/UniversityRepository.java
src/main/java/comatching/comatching3/users/repository/UsersRepository.java

관리자, 유저 레포지토리 추가

---

src/main/java/comatching/comatching3/config/SecurityConfig.java
src/main/java/comatching/comatching3/users/auth/jwt/JwtFilter.java
src/main/java/comatching/comatching3/users/controller/UserController.java
src/main/java/comatching/comatching3/users/service/UserService.java

CMT-21 feat: 유저 포인트 조회 메소드 추가

---

build.gradle
src/main/java/comatching/comatching3/admin/controller/AdminController.java
src/main/java/comatching/comatching3/admin/controller/UniversityController.java
src/main/java/comatching/comatching3/admin/dto/request/AdminLoginReq.java
src/main/java/comatching/comatching3/admin/dto/request/AdminRegisterReq.java
src/main/java/comatching/comatching3/admin/dto/request/EmailVerifyReq.java
src/main/java/comatching/comatching3/admin/dto/request/SchoolEmailReq.java
src/main/java/comatching/comatching3/admin/dto/request/UniversityReq.java
src/main/java/comatching/comatching3/admin/dto/response/AdminInfoRes.java
src/main/java/comatching/comatching3/admin/dto/response/EmailTokenRes.java
src/main/java/comatching/comatching3/admin/dto/response/TokenRes.java
src/main/java/comatching/comatching3/admin/entity/Admin.java
src/main/java/comatching/comatching3/admin/enums/AdminRole.java
src/main/java/comatching/comatching3/admin/exception/AdminExceptionHandler.java
src/main/java/comatching/comatching3/admin/exception/UniversityNotExistException.java
src/main/java/comatching/comatching3/admin/repository/AdminRepository.java
src/main/java/comatching/comatching3/admin/service/AdminService.java
src/main/java/comatching/comatching3/admin/service/UniversityService.java
src/main/java/comatching/comatching3/aws/AwsS3Service.java
src/main/java/comatching/comatching3/config/SecurityConfig.java
src/main/java/comatching/comatching3/users/auth/jwt/JwtFilter.java
src/main/java/comatching/comatching3/users/auth/jwt/JwtUtil.java
src/main/java/comatching/comatching3/users/auth/oauth2/dto/CustomOAuth2User.java
src/main/java/comatching/comatching3/users/auth/oauth2/dto/UserDto.java
src/main/java/comatching/comatching3/users/auth/oauth2/service/CustomOAuth2UserService.java
src/main/java/comatching/comatching3/users/auth/refresh_token/service/RefreshTokenService.java
src/main/java/comatching/comatching3/util/EmailUtil.java
src/main/java/comatching/comatching3/util/ResponseCode.java

Admin 회원가입, 로그인, 이메일 인증 구현 완료
관리자 내 정보 조회까지 완료

CMT-26 관리자 인증

---

src/main/java/comatching/comatching3/users/dto/messageQueue/UserCrudMsg.java
src/main/java/comatching/comatching3/users/enums/UserCrudType.java
src/main/java/comatching/comatching3/util/RabbitMQ/MatchRabbitMQUtil.java
src/main/java/comatching/comatching3/util/RabbitMQ/RabbitMQUtil.java
src/main/java/comatching/comatching3/util/RabbitMQ/UserCrudRabbitMQUtil.java

* CorrelationData를 사용한 ack/nack 보상 작업
* crud용 메세지 큐 publish 메서드 추가

사용자 정보 AI csv 반영 기능

---

.gitignore
build.gradle
src/main/java/comatching/comatching3/admin/controller/AdminController.java
src/main/java/comatching/comatching3/admin/controller/OperatorController.java
src/main/java/comatching/comatching3/admin/controller/PasswordViewController.java
src/main/java/comatching/comatching3/admin/dto/request/AdminRegisterReq.java
src/main/java/comatching/comatching3/admin/dto/request/ResetPasswordReq.java
src/main/java/comatching/comatching3/admin/dto/request/SendResetPasswordEmailReq.java
src/main/java/comatching/comatching3/admin/dto/response/OperatorRes.java
src/main/java/comatching/comatching3/admin/entity/Admin.java
src/main/java/comatching/comatching3/admin/repository/AdminRepository.java
src/main/java/comatching/comatching3/admin/service/AdminService.java
src/main/java/comatching/comatching3/admin/service/OperatorService.java
src/main/java/comatching/comatching3/users/service/UserService.java
src/main/java/comatching/comatching3/util/ResponseCode.java
src/main/java/comatching/comatching3/util/security/SecurityUtil.java
src/main/resources/static/css/styles.css
src/main/resources/templates/admin_password/resetPasswordForm.html
src/main/resources/templates/admin_password/tokenExpired.html

관리자 기능 완성
- 오퍼레이터 회원가입 
- 오퍼레이터 가입 승인 기능
- 관리자 아이디 변경에 관한 개발 및 수정
- 관리자 아이디 찾는 기능
- 관리자 정보 조회 기능에 대한 수정
- 비밀번호 재설정 기능
수정 필요한 부분
- 이메일 양식
- 비밀번호 변경 폼 스타일
- 비밀번호 재설정 횟수 제한
- 아이디 찾을 때 일부공개로 변경
- 비밀번호 변경 후 관리자 로그인 페이지로 이동하도록 변경 (지금은 일단 홈으로 이동)

CMT-26 관리자 관련 기능 개발

---

.gitignore
docker-compose.yml
src/main/java/comatching/comatching3/charge/controller/ChargeController.java
src/main/java/comatching/comatching3/charge/controller/WebTestController.java
src/main/java/comatching/comatching3/charge/dto/request/ChargeCancelReq.java
src/main/java/comatching/comatching3/charge/service/ChargeService.java
src/main/java/comatching/comatching3/config/SecurityConfig.java
src/main/java/comatching/comatching3/users/auth/oauth2/handler/OAuth2SuccessHandler.java
src/main/java/comatching/comatching3/users/service/UserService.java
src/main/resources/templates/loginSuccess.html

- docker-compose 설정
- 임시 로그인 성공 페이지
- 포인트 충전 요청 승인 거부 기능

2차 배포용 ci 설정

---

src/main/java/comatching/comatching3/history/controller/HistoryController.java
src/main/java/comatching/comatching3/history/dto/res/MatchHistoryRes.java
src/main/java/comatching/comatching3/history/entity/MatchingHistory.java
src/main/java/comatching/comatching3/history/repository/MatchingHistoryRepository.java
src/main/java/comatching/comatching3/history/service/HistoryService.java
src/main/java/comatching/comatching3/match/controller/MatchAdminController.java
src/main/java/comatching/comatching3/match/dto/messageQueue/MatchRequestMsg.java
src/main/java/comatching/comatching3/match/dto/messageQueue/MatchResponseMsg.java
src/main/java/comatching/comatching3/match/service/MatchService.java
src/main/java/comatching/comatching3/users/enums/Hobby.java
src/main/java/comatching/comatching3/util/RabbitMQ/MatchRabbitMQUtil.java
src/main/java/comatching/comatching3/util/ResponseCode.java
src/test/java/comatching/comatching3/match/MatchTest.java

- 매칭 내역 조회 기능 추가
- AI 서버 응답 포맷 변경 반영
- Hobby Dto내 문자열 변환처리 추가

매칭내역 조회 추가 및 AI 서버 변경 반영

---

src/main/java/comatching/comatching3/config/WebSocketConfig.java
src/main/java/comatching/comatching3/users/auth/jwt/JwtUtil.java

chore : 자잘한 수정

---

src/main/java/comatching/comatching3/charge/service/ChargeService.java
src/main/java/comatching/comatching3/history/controller/HistoryController.java
src/main/java/comatching/comatching3/history/dto/res/PointHistoryRes.java
src/main/java/comatching/comatching3/history/entity/PointHistory.java
src/main/java/comatching/comatching3/history/enums/PointHistoryType.java
src/main/java/comatching/comatching3/history/repository/PointHistoryRepository.java
src/main/java/comatching/comatching3/history/service/HistoryService.java
src/main/java/comatching/comatching3/users/auth/jwt/JwtFilter.java
src/main/java/comatching/comatching3/users/service/UserService.java

feat : 포인트 히스토리 기능 추가

---

src/main/java/comatching/comatching3/users/auth/jwt/JwtFilter.java
src/main/java/comatching/comatching3/users/service/UserService.java
src/main/java/comatching/comatching3/util/ResponseCode.java

이벤트 중복참여 못하도록 수정
리프레시토큰 생성하지 않도록 수정

이벤트 및 필터 수정

---

src/main/java/comatching/comatching3/config/SecurityConfig.java
src/main/java/comatching/comatching3/history/dto/res/MatchHistoryRes.java
src/main/java/comatching/comatching3/history/entity/MatchingHistory.java
src/main/java/comatching/comatching3/match/dto/messageQueue/MatchRequestMsg.java
src/main/java/comatching/comatching3/match/dto/request/AdminMatchReq.java
src/main/java/comatching/comatching3/match/dto/request/MatchReq.java
src/main/java/comatching/comatching3/match/dto/response/MatchRes.java
src/main/java/comatching/comatching3/match/service/MatchService.java
src/main/java/comatching/comatching3/users/auth/jwt/JwtFilter.java
src/main/java/comatching/comatching3/users/dto/UserInfoRes.java
src/main/java/comatching/comatching3/users/dto/messageQueue/UserCrudMsg.java
src/main/java/comatching/comatching3/users/entity/Hobby.java
src/main/java/comatching/comatching3/users/entity/UserAiFeature.java
src/main/java/comatching/comatching3/users/enums/HobbyEnum.java
src/main/java/comatching/comatching3/users/repository/HobbyRepository.java
src/main/java/comatching/comatching3/users/service/UserService.java
src/main/java/comatching/comatching3/util/HobbyListConverter.java
src/test/java/comatching/comatching3/match/MatchTest.java

원자성 보존을 위해 기존의 List 형식의 Hobby 대신 테이블을 새로 만듦

feat : Hobby 테이블 추가

---

src/main/java/comatching/comatching3/config/AppConfig.java
src/main/java/comatching/comatching3/config/SecurityConfig.java
src/main/java/comatching/comatching3/users/auth/oauth2/provider/OAuth2Provider.java
src/main/java/comatching/comatching3/users/auth/oauth2/provider/OAuth2ProviderFactory.java
src/main/java/comatching/comatching3/users/auth/oauth2/provider/google/GoogleUser.java
src/main/java/comatching/comatching3/users/auth/oauth2/provider/kakao/KakaoLogoutService.java
src/main/java/comatching/comatching3/users/auth/oauth2/provider/kakao/KakaoUser.java
src/main/java/comatching/comatching3/users/auth/oauth2/provider/naver/NaverUser.java
src/main/java/comatching/comatching3/users/auth/oauth2/service/LogoutService.java
src/main/java/comatching/comatching3/users/auth/oauth2/service/LogoutServiceFactory.java
src/main/java/comatching/comatching3/users/controller/UserController.java
src/main/java/comatching/comatching3/users/service/UserService.java
src/main/java/comatching/comatching3/util/ResponseCode.java
src/main/resources/static/index.html

로그아웃 기능 추가
전략패턴 적용했는데 카카오 말고는 로그아웃 api 제공을 안해서 아쉽다.

feat($logout): 로그아웃 기능 추가

---

src/main/java/comatching/comatching3/admin/controller/EventController.java
src/main/java/comatching/comatching3/admin/dto/request/DiscountEventRegisterReq.java
src/main/java/comatching/comatching3/admin/entity/event/DiscountEvent.java
src/main/java/comatching/comatching3/admin/entity/event/Event.java
src/main/java/comatching/comatching3/admin/entity/event/EventParticipation.java
src/main/java/comatching/comatching3/admin/enums/EventType.java
src/main/java/comatching/comatching3/admin/repository/EventParticipationRepository.java
src/main/java/comatching/comatching3/admin/repository/EventRepository.java
src/main/java/comatching/comatching3/admin/service/EventService.java
src/main/java/comatching/comatching3/util/ResponseCode.java

[x] 이벤트 엔티티 정규화 및 상속 / 엔티티 맵핑 추가

관리자 이벤트 추가 기능

---

src/main/java/comatching/comatching3/admin/controller/EventController.java
src/main/java/comatching/comatching3/admin/dto/request/DiscountEventRegisterReq.java
src/main/java/comatching/comatching3/admin/dto/response/EventRes.java
src/main/java/comatching/comatching3/admin/entity/event/DiscountEvent.java
src/main/java/comatching/comatching3/admin/entity/event/Event.java
src/main/java/comatching/comatching3/admin/repository/EventRepository.java
src/main/java/comatching/comatching3/admin/service/EventService.java
src/main/java/comatching/comatching3/util/ResponseCode.java

1. 이벤트 JPA 상속 에러 해결
2. 이벤트 추가 로직 수정
3. 관리자 이벤트 조회 기능 추가

이벤트 조회 및 추가 기능 개발

---

src/main/java/comatching/comatching3/users/dto/messageQueue/CategoryReqMsg.java
src/main/java/comatching/comatching3/users/dto/messageQueue/CategoryResMsg.java
src/main/java/comatching/comatching3/users/dto/messageQueue/UserCrudMsg.java
src/main/java/comatching/comatching3/util/RabbitMQ/CategoryRabbitMQUtil.java

유저 소분류 -> 대분류 변환을 위한 RabbitMQ 통신 Util 작성

유저 소분류 변환 메서드 추가

---

build.gradle
src/main/java/comatching/comatching3/auth/flutter/controller/FlutterController.java
src/main/java/comatching/comatching3/auth/oauth2/provider/ProviderUser.java
src/main/java/comatching/comatching3/auth/oauth2/provider/apple/AppleUser.java
src/main/java/comatching/comatching3/auth/oauth2/provider/google/GoogleUser.java
src/main/java/comatching/comatching3/auth/oauth2/provider/kakao/KakaoUser.java
src/main/java/comatching/comatching3/auth/oauth2/provider/naver/NaverUser.java
src/main/java/comatching/comatching3/auth/oauth2/service/CustomOAuth2UserService.java
src/main/java/comatching/comatching3/pay/repository/OrderRepository.java
src/main/java/comatching/comatching3/pay/service/PayHistoryService.java
src/main/java/comatching/comatching3/pay/service/PayService.java
src/main/java/comatching/comatching3/users/controller/ReportController.java
src/main/java/comatching/comatching3/users/dto/messageQueue/CategoryReqMsg.java
src/main/java/comatching/comatching3/users/dto/request/ReportReq.java
src/main/java/comatching/comatching3/users/entity/Report.java
src/main/java/comatching/comatching3/users/entity/Users.java
src/main/java/comatching/comatching3/users/repository/ReportRepository.java
src/main/java/comatching/comatching3/users/service/ReportService.java
src/main/java/comatching/comatching3/users/service/UserService.java

- 관리자 관련 수정
- 로그인 정상화
- 신고 기능 미완

chore: 자잘한 수정

---

docker-compose.yml
src/main/java/comatching/comatching3/auth/oauth2/handler/OAuth2SuccessHandler.java

chore: 도커 파일 수정

---

docker-compose.yml
src/main/java/comatching/comatching3/event/controller/AdminEventController.java
src/main/java/comatching/comatching3/event/dto/req/DiscountEventRegisterReq.java
src/main/java/comatching/comatching3/event/dto/res/DiscountEventRes.java
src/main/java/comatching/comatching3/event/service/AdminEventService.java

- Docker network 이름 변경 
- docker-compose down시 network 재시작 방지

Docker 파일 수정

---

src/main/java/comatching/comatching3/admin/controller/OperatorController.java
src/main/java/comatching/comatching3/admin/service/OperatorService.java
src/main/java/comatching/comatching3/auth/oauth2/provider/kakao/KakaoApiService.java
src/main/resources/templates/admin_password/tokenExpired.html

chore: 배포 관련 수정

---

src/main/java/comatching/comatching3/charge/controller/TempChargeController.java
src/main/java/comatching/comatching3/charge/dto/request/ChargeApprovalReq.java
src/main/java/comatching/comatching3/charge/dto/request/TempChargeApprovalReq.java
src/main/java/comatching/comatching3/charge/dto/request/TempChargeRequest.java
src/main/java/comatching/comatching3/charge/dto/response/ChargePendingInfo.java
src/main/java/comatching/comatching3/charge/dto/response/TempChargeRes.java
src/main/java/comatching/comatching3/charge/entity/ChargeRequest.java
src/main/java/comatching/comatching3/charge/repository/ChargeRequestRepository.java
src/main/java/comatching/comatching3/charge/service/TempChargeService.java
src/main/java/comatching/comatching3/event/batch/DailyPointItemProcessor.java
src/main/java/comatching/comatching3/pay/batch/DailyPointBatchConfig.java
src/main/java/comatching/comatching3/pay/controller/PayHistoryController.java
src/main/java/comatching/comatching3/pay/service/PayHistoryService.java
src/main/java/comatching/comatching3/pay/service/PayService.java
src/main/java/comatching/comatching3/users/entity/Users.java
src/main/java/comatching/comatching3/util/ResponseCode.java

- 자체 결제 기능 추가
- 일일 충전한도 설정
- 일일 충전한도 배치처리

feat: 자체 결제 기능 추가

---

src/main/java/comatching/comatching3/charge/repository/ChargeRequestRepository.java
src/main/java/comatching/comatching3/charge/service/TempChargeService.java
src/main/java/comatching/comatching3/util/ResponseCode.java

feat: 결제 중복 요청 불가

---

src/main/java/comatching/comatching3/charge/service/TempChargeService.java
src/main/java/comatching/comatching3/util/ResponseCode.java

chore: 천원 버튼 응답 추가

---

src/main/java/comatching/comatching3/users/dto/messageQueue/CategoryReqMsg.java
src/main/java/comatching/comatching3/users/dto/messageQueue/CategoryResMsg.java
src/main/java/comatching/comatching3/users/service/UserService.java
src/main/java/comatching/comatching3/util/RabbitMQ/CategoryRabbitMQUtil.java

classify rabbitMQ 응답 구조 변경 사항 반영
- CategoryResMsg 응답 `stateCode`, `message` 필드 추가
- usersService CategoryResMsg 활용 코드 변경

($Category) classify 응답 구조 변경

---

src/main/java/comatching/comatching3/notice/domain/entity/Notice.java
src/main/java/comatching/comatching3/notice/domain/entity/NoticeConfirm.java
src/main/java/comatching/comatching3/notice/domain/enums/NoticeType.java
src/main/java/comatching/comatching3/notice/dto/response/NoticeRes.java
src/main/java/comatching/comatching3/notice/repository/NoticeConfirmRepository.java
src/main/java/comatching/comatching3/notice/repository/NoticeRepository.java
src/main/java/comatching/comatching3/notice/service/AdminNoticeService.java

- 공지사항 도메인 정의 및 데이터 추가 
- 관리자 공지사항 추가 기능
`Notice`, `NoticeConfirm` 엔티티
- `Notice` : 공지사항 정보를 담은 Table
- `NoticeConfirm` : 유저별 공지사항 확인 여부
관리자 공지사항(notice)추가 로직
1. notice 테이블 생성
2. 소속 학교 유저에 대해서 noticeConfirm 엔티티 배치 생성

(Notice) 공지사항 추가 기능 개발

---

src/main/java/comatching/comatching3/users/service/UserService.java

chore: 코드 병합

---

src/main/java/comatching/comatching3/users/repository/UserAiFeatureRepository.java

chore: 매칭 수정
